import slsk from "slsk-client";
import { randomBytes } from "crypto";
import { dbOps } from "../config/db-helpers.js";
import path from "path";
import fs from "fs/promises";
import { Readable } from "stream";

export class SimpleSoulseekClient {
  constructor() {
    this.client = null;
    this.connected = false;
    this.config = null;
    this.updateConfig();
  }

  ensureCredentials() {
    const settings = dbOps.getSettings();
    const dbConfig = settings.integrations?.soulseek || {};
    const envUsername = process.env.SOULSEEK_USERNAME || "";
    const envPassword = process.env.SOULSEEK_PASSWORD || "";
    const hasEnv = !!(envUsername || envPassword);
    let username = envUsername || dbConfig.username || "";
    let password = envPassword || dbConfig.password || "";
    const looksAuto =
      typeof dbConfig.username === "string" &&
      dbConfig.username.startsWith("aurral_");
    let autoGenerated =
      !hasEnv && (dbConfig.autoGenerated === true || looksAuto);

    if (!username || !password) {
      username = username || `aurral_${randomBytes(8).toString("hex")}`;
      password = password || randomBytes(16).toString("hex");
      autoGenerated = true;
      const current = dbOps.getSettings();
      const integrations = {
        ...(current.integrations || {}),
        soulseek: { username, password, autoGenerated: true },
      };
      dbOps.updateSettings({ ...current, integrations });
    }

    return { username, password, autoGenerated };
  }

  updateConfig() {
    const { username, password, autoGenerated } = this.ensureCredentials();
    this.config = { username, password, autoGenerated };
  }

  isConfigured() {
    this.updateConfig();
    return !!(this.config.username && this.config.password);
  }

  async connect(retryInvalidPass = true) {
    if (this.connected && this.client) {
      return true;
    }

    if (!this.isConfigured()) {
      throw new Error("Soulseek credentials not configured");
    }

    return new Promise((resolve, reject) => {
      slsk.connect(
        {
          user: this.config.username,
          pass: this.config.password,
        },
        async (err, client) => {
          if (err) {
            this.connected = false;
            this.client = null;
            if (
              retryInvalidPass &&
              this.config?.autoGenerated &&
              this.isInvalidPass(err)
            ) {
              try {
                await this.regenerateCredentials();
                const ok = await this.connect(false);
                resolve(ok);
                return;
              } catch {
                reject(err);
                return;
              }
            }
            reject(err);
            return;
          }
          this.client = client;
          this.connected = true;
          resolve(true);
        },
      );
    });
  }

  isInvalidPass(error) {
    const message = error?.message || "";
    return String(message).includes("INVALIDPASS");
  }

  async regenerateCredentials() {
    const username = `aurral_${randomBytes(8).toString("hex")}`;
    const password = randomBytes(16).toString("hex");
    const current = dbOps.getSettings();
    const integrations = {
      ...(current.integrations || {}),
      soulseek: { username, password, autoGenerated: true },
    };
    dbOps.updateSettings({ ...current, integrations });
    this.config = { username, password, autoGenerated: true };
    return { username, password };
  }

  async disconnect() {
    if (this.client && this.connected) {
      try {
        this.client.destroy();
      } catch (err) {}
      try {
        slsk.disconnect();
      } catch (err) {}
      this.client = null;
      this.connected = false;
    }
    try {
      const { default: stack } = await import("slsk-client/lib/stack.js");
      stack.search = {};
      stack.download = {};
      stack.downloadTokens = {};
      stack.peerSearchMatches = {};
      stack.peerSearchRequests = [];
      stack.login = undefined;
      stack.currentLogin = undefined;
    } catch (err) {}
  }

  isConnected() {
    return this.connected && this.client !== null;
  }

  _getSearchTimeoutMs() {
    const raw = Number(process.env.SOULSEEK_SEARCH_TIMEOUT_MS);
    if (Number.isFinite(raw) && raw >= 1000) return raw;
    return 10000;
  }

  _getDownloadTimeoutMs() {
    const raw = Number(process.env.SOULSEEK_DOWNLOAD_TIMEOUT_MS);
    if (Number.isFinite(raw) && raw >= 10000) return raw;
    return 420000;
  }

  _getMatchScanLimit() {
    const raw = Number(process.env.SOULSEEK_MATCH_SCAN_LIMIT);
    if (Number.isFinite(raw) && raw >= 50) {
      return Math.min(Math.floor(raw), 1000);
    }
    return 150;
  }

  async search(artistName, trackName) {
    if (!this.isConnected()) {
      await this.connect();
    }

    const query = `${artistName} ${trackName}`;

    return new Promise((resolve, reject) => {
      this.client.search(
        {
          req: query,
          timeout: this._getSearchTimeoutMs(),
        },
        (err, results) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(results || []);
        },
      );
    });
  }

  pickBestMatch(results, trackName) {
    const matches = this.pickBestMatches(results, trackName, 1);
    return matches[0] || null;
  }

  pickBestMatches(results, trackName, limit = 5) {
    if (!Array.isArray(results) || results.length === 0) {
      return [];
    }
    const max = Number.isFinite(Number(limit)) ? Math.max(1, Number(limit)) : 5;
    const scanLimit = this._getMatchScanLimit();
    const source =
      results.length > scanLimit ? results.slice(0, scanLimit) : results;
    const trackNameLower = String(trackName || "")
      .toLowerCase()
      .trim();
    const qualityOrder = { ".flac": 0, ".mp3": 1, ".m4a": 2, ".ogg": 3 };
    const score = (item) => {
      const file = String(item?.file || "").toLowerCase();
      const ext = path.extname(file).toLowerCase();
      const quality = qualityOrder[ext] ?? 99;
      const hasTrack = trackNameLower ? file.includes(trackNameLower) : false;
      const hasSlots = item?.slots ? 0 : 1;
      const fileSize = Number(item?.size || 0);
      const sizePenalty =
        fileSize > 0 ? Math.max(0, 500000 - fileSize) : 500000;
      return {
        hasTrack: hasTrack ? 0 : 1,
        quality,
        hasSlots,
        sizePenalty,
      };
    };
    const compareScore = (sa, sb) => {
      if (sa.hasTrack !== sb.hasTrack) return sa.hasTrack - sb.hasTrack;
      if (sa.quality !== sb.quality) return sa.quality - sb.quality;
      if (sa.hasSlots !== sb.hasSlots) return sa.hasSlots - sb.hasSlots;
      if (sa.sizePenalty !== sb.sizePenalty)
        return sa.sizePenalty - sb.sizePenalty;
      return 0;
    };
    const top = [];
    const topScores = [];
    for (const item of source) {
      const itemScore = score(item);
      let insertAt = top.length;
      for (let i = 0; i < top.length; i += 1) {
        if (compareScore(itemScore, topScores[i]) < 0) {
          insertAt = i;
          break;
        }
      }
      if (insertAt >= max && top.length >= max) continue;
      top.splice(insertAt, 0, item);
      topScores.splice(insertAt, 0, itemScore);
      if (top.length > max) {
        top.pop();
        topScores.pop();
      }
    }
    return top;
  }

  async download(result, destinationPath, onProgress = null) {
    await this.connect();

    const absPath = path.resolve(destinationPath);
    const dir = path.dirname(absPath);
    await fs.mkdir(dir, { recursive: true });

    const DOWNLOAD_TIMEOUT_MS = this._getDownloadTimeoutMs();
    const expectedBytes = Number(result?.size || 0);
    const progressEnabled =
      typeof onProgress === "function" && expectedBytes > 0;

    try {
      const filePath = await new Promise((resolve, reject) => {
        let settled = false;
        let timeoutId = null;
        let lastProgress = -1;
        let downloadedBytes = 0;
        let lastProgressEmitAt = 0;
        const progressStream = progressEnabled
          ? new Readable({
              read() {},
            })
          : null;
        const emitProgress = (value) => {
          if (!progressEnabled) return;
          const next = Math.max(
            0,
            Math.min(100, Math.floor(Number(value) || 0)),
          );
          if (next <= lastProgress) return;
          lastProgress = next;
          onProgress(next);
        };
        if (progressStream) {
          progressStream.on("data", (chunk) => {
            const size = Buffer.isBuffer(chunk)
              ? chunk.length
              : Number(chunk?.length || 0);
            if (!Number.isFinite(size) || size <= 0) return;
            downloadedBytes += size;
            const now = Date.now();
            const pct = Math.floor((downloadedBytes / expectedBytes) * 100);
            const bounded = Math.max(0, Math.min(99, pct));
            if (bounded > lastProgress && now - lastProgressEmitAt >= 750) {
              lastProgressEmitAt = now;
              emitProgress(bounded);
            }
          });
        }

        const settle = (fn) => (val) => {
          if (settled) return;
          settled = true;
          if (timeoutId) clearTimeout(timeoutId);
          fn(val);
        };

        timeoutId = setTimeout(async () => {
          if (settled) return;
          const stat = await fs.stat(absPath).catch(() => null);
          if (stat && stat.size > 0) {
            settle(resolve)(absPath);
          } else {
            settle(reject)(new Error("Download timeout"));
          }
        }, DOWNLOAD_TIMEOUT_MS);

        this.client.download(
          { file: result, path: absPath },
          (err, down) => {
            if (err) {
              settle(reject)(err);
              return;
            }
            emitProgress(100);
            const resolvedPath =
              typeof down?.path === "string" && down.path.trim()
                ? path.resolve(down.path)
                : absPath;
            settle(resolve)(resolvedPath);
          },
          progressStream || undefined,
        );
      });

      return filePath;
    } catch (err) {
      throw err;
    }
  }
}

export const soulseekClient = new SimpleSoulseekClient();
