import slsk from "slsk-client";
import { randomBytes } from "crypto";
import { dbOps } from "../config/db-helpers.js";
import path from "path";
import fs from "fs/promises";
import { createWriteStream } from "fs";

export class SimpleSoulseekClient {
  constructor() {
    this.client = null;
    this.connected = false;
    this.config = null;
    this.updateConfig();
  }

  ensureCredentials() {
    const settings = dbOps.getSettings();
    const dbConfig = settings.integrations?.soulseek || {};
    const envUsername = process.env.SOULSEEK_USERNAME || "";
    const envPassword = process.env.SOULSEEK_PASSWORD || "";
    const hasEnv = !!(envUsername || envPassword);
    let username = envUsername || dbConfig.username || "";
    let password = envPassword || dbConfig.password || "";
    const looksAuto =
      typeof dbConfig.username === "string" &&
      dbConfig.username.startsWith("aurral_");
    let autoGenerated =
      !hasEnv && (dbConfig.autoGenerated === true || looksAuto);

    if (!username || !password) {
      username = username || `aurral_${randomBytes(8).toString("hex")}`;
      password = password || randomBytes(16).toString("hex");
      autoGenerated = true;
      const current = dbOps.getSettings();
      const integrations = {
        ...(current.integrations || {}),
        soulseek: { username, password, autoGenerated: true },
      };
      dbOps.updateSettings({ ...current, integrations });
    }

    return { username, password, autoGenerated };
  }

  updateConfig() {
    const { username, password, autoGenerated } = this.ensureCredentials();
    this.config = { username, password, autoGenerated };
  }

  isConfigured() {
    this.updateConfig();
    return !!(this.config.username && this.config.password);
  }

  async connect(retryInvalidPass = true) {
    if (this.connected && this.client) {
      return true;
    }

    if (!this.isConfigured()) {
      throw new Error("Soulseek credentials not configured");
    }

    return new Promise((resolve, reject) => {
      slsk.connect(
        {
          user: this.config.username,
          pass: this.config.password,
        },
        async (err, client) => {
          if (err) {
            this.connected = false;
            this.client = null;
            if (
              retryInvalidPass &&
              this.config?.autoGenerated &&
              this.isInvalidPass(err)
            ) {
              try {
                await this.regenerateCredentials();
                const ok = await this.connect(false);
                resolve(ok);
                return;
              } catch {
                reject(err);
                return;
              }
            }
            reject(err);
            return;
          }
          this.client = client;
          this.connected = true;
          resolve(true);
        },
      );
    });
  }

  isInvalidPass(error) {
    const message = error?.message || "";
    return String(message).includes("INVALIDPASS");
  }

  async regenerateCredentials() {
    const username = `aurral_${randomBytes(8).toString("hex")}`;
    const password = randomBytes(16).toString("hex");
    const current = dbOps.getSettings();
    const integrations = {
      ...(current.integrations || {}),
      soulseek: { username, password, autoGenerated: true },
    };
    dbOps.updateSettings({ ...current, integrations });
    this.config = { username, password, autoGenerated: true };
    return { username, password };
  }

  async disconnect() {
    if (this.client && this.connected) {
      try {
        this.client.destroy();
      } catch (err) {}
      try {
        slsk.disconnect();
      } catch (err) {}
      this.client = null;
      this.connected = false;
    }
    try {
      const { default: stack } = await import("slsk-client/lib/stack.js");
      stack.search = {};
      stack.download = {};
      stack.downloadTokens = {};
      stack.peerSearchMatches = {};
      stack.peerSearchRequests = [];
      stack.login = undefined;
      stack.currentLogin = undefined;
    } catch (err) {}
  }

  isConnected() {
    return this.connected && this.client !== null;
  }

  _getSearchTimeoutMs() {
    const raw = Number(process.env.SOULSEEK_SEARCH_TIMEOUT_MS);
    if (Number.isFinite(raw) && raw >= 1000) return raw;
    return 10000;
  }

  _getDownloadTimeoutMs() {
    const raw = Number(process.env.SOULSEEK_DOWNLOAD_TIMEOUT_MS);
    if (Number.isFinite(raw) && raw >= 10000) return raw;
    return 420000;
  }

  async search(artistName, trackName) {
    if (!this.isConnected()) {
      await this.connect();
    }

    const query = `${artistName} ${trackName}`;

    return new Promise((resolve, reject) => {
      this.client.search(
        {
          req: query,
          timeout: this._getSearchTimeoutMs(),
        },
        (err, results) => {
          if (err) {
            reject(err);
            return;
          }
          resolve(results || []);
        },
      );
    });
  }

  pickBestMatch(results, trackName) {
    const matches = this.pickBestMatches(results, trackName, 1);
    return matches[0] || null;
  }

  pickBestMatches(results, trackName, limit = 5) {
    if (!Array.isArray(results) || results.length === 0) {
      return [];
    }
    const max = Number.isFinite(Number(limit)) ? Math.max(1, Number(limit)) : 5;
    const trackNameLower = String(trackName || "")
      .toLowerCase()
      .trim();
    const qualityOrder = { ".flac": 0, ".mp3": 1, ".m4a": 2, ".ogg": 3 };
    const score = (item) => {
      const file = String(item?.file || "").toLowerCase();
      const ext = path.extname(file).toLowerCase();
      const quality = qualityOrder[ext] ?? 99;
      const hasTrack = trackNameLower ? file.includes(trackNameLower) : false;
      const hasSlots = item?.slots ? 0 : 1;
      const fileSize = Number(item?.size || 0);
      const sizePenalty =
        fileSize > 0 ? Math.max(0, 500000 - fileSize) : 500000;
      return {
        hasTrack: hasTrack ? 0 : 1,
        quality,
        hasSlots,
        sizePenalty,
      };
    };
    const compareScore = (sa, sb) => {
      if (sa.hasTrack !== sb.hasTrack) return sa.hasTrack - sb.hasTrack;
      if (sa.quality !== sb.quality) return sa.quality - sb.quality;
      if (sa.hasSlots !== sb.hasSlots) return sa.hasSlots - sb.hasSlots;
      if (sa.sizePenalty !== sb.sizePenalty)
        return sa.sizePenalty - sb.sizePenalty;
      return 0;
    };
    const top = [];
    const topScores = [];
    for (const item of results) {
      const itemScore = score(item);
      let insertAt = top.length;
      for (let i = 0; i < top.length; i += 1) {
        if (compareScore(itemScore, topScores[i]) < 0) {
          insertAt = i;
          break;
        }
      }
      if (insertAt >= max && top.length >= max) continue;
      top.splice(insertAt, 0, item);
      topScores.splice(insertAt, 0, itemScore);
      if (top.length > max) {
        top.pop();
        topScores.pop();
      }
    }
    return top;
  }

  async download(result, destinationPath) {
    await this.connect();

    const absPath = path.resolve(destinationPath);
    const dir = path.dirname(absPath);
    await fs.mkdir(dir, { recursive: true });

    const DOWNLOAD_TIMEOUT_MS = this._getDownloadTimeoutMs();

    try {
      const filePath = await new Promise((resolve, reject) => {
        let settled = false;
        let timeoutId = null;

        const settle = (fn) => (val) => {
          if (settled) return;
          settled = true;
          if (timeoutId) clearTimeout(timeoutId);
          fn(val);
        };

        timeoutId = setTimeout(async () => {
          if (settled) return;
          const stat = await fs.stat(absPath).catch(() => null);
          if (stat && stat.size > 0) {
            settle(resolve)(absPath);
          } else {
            settle(reject)(new Error("Download timeout"));
          }
        }, DOWNLOAD_TIMEOUT_MS);

        this.client.downloadStream({ file: result }, (err, readStream) => {
          if (err) {
            settle(reject)(err);
            return;
          }

          const writeStream = createWriteStream(absPath);

          writeStream.on("error", (e) => {
            if (e.code === "ERR_STREAM_DESTROYED" || settled) return;
            settle(reject)(e);
          });
          readStream.on("error", (e) => {
            if (e.code === "ERR_STREAM_DESTROYED" || settled) return;
            settle(reject)(e);
          });
          writeStream.on("finish", () => settle(resolve)(absPath));

          readStream.pipe(writeStream);
        });
      });

      return filePath;
    } catch (err) {
      throw err;
    }
  }
}

export const soulseekClient = new SimpleSoulseekClient();
