export const EDITORIAL_PLAYLIST_PRESETS = [
  {
    id: "top-rock",
    name: "Today's Top Rock",
    description: "The biggest rock tracks right now",
    tag: "rock",
    size: 30,
    type: "genre",
  },
  {
    id: "top-indie",
    name: "All-Time Indie",
    description: "Essential indie tracks across decades",
    tag: "indie",
    size: 30,
    type: "genre",
  },
  {
    id: "top-hiphop",
    name: "Hip-Hop Essentials",
    description: "The tracks defining hip-hop today",
    tag: "hip-hop",
    size: 30,
    type: "genre",
  },
  {
    id: "top-electronic",
    name: "Electronic Vibes",
    description: "Electronic and dance floor favorites",
    tag: "electronic",
    size: 30,
    type: "genre",
  },
  {
    id: "top-pop",
    name: "Pop Hits",
    description: "The pop tracks everyone's playing",
    tag: "pop",
    size: 30,
    type: "genre",
  },
  {
    id: "top-rnb",
    name: "R&B Soul",
    description: "Smooth R&B and soul standouts",
    tag: "rnb",
    size: 30,
    type: "genre",
  },
  {
    id: "top-metal",
    name: "Metal Mayhem",
    description: "Heavy riffs and thunderous drums",
    tag: "metal",
    size: 30,
    type: "genre",
  },
  {
    id: "top-jazz",
    name: "Jazz Classics",
    description: "Timeless jazz from the greats",
    tag: "jazz",
    size: 30,
    type: "genre",
  },
  {
    id: "era-80s",
    name: "80s Anthems",
    description: "The decade of big sounds and bigger hair",
    tag: "80s",
    size: 30,
    type: "era",
  },
  {
    id: "era-90s",
    name: "90s Nostalgia",
    description: "Grunge, Britpop, and golden-era hip-hop",
    tag: "90s",
    size: 30,
    type: "era",
  },
  {
    id: "mood-chill",
    name: "Chill Vibes",
    description: "Laid-back tracks for unwinding",
    tag: "chill",
    size: 30,
    type: "mood",
  },
  {
    id: "mood-energetic",
    name: "Workout Energy",
    description: "High-energy tracks to power through",
    tag: "workout",
    size: 30,
    type: "mood",
  },
];
