export const EDITORIAL_PLAYLIST_POOL = [
  {
    id: "top-rock",
    name: "Today's Top Rock",
    description: "The biggest rock tracks right now",
    tag: "rock",
    size: 20,
    type: "genre",
  },
  {
    id: "top-indie",
    name: "All-Time Indie",
    description: "Essential indie tracks across decades",
    tag: "indie",
    size: 20,
    type: "genre",
  },
  {
    id: "top-hiphop",
    name: "Hip-Hop Essentials",
    description: "The tracks defining hip-hop today",
    tag: "hip-hop",
    size: 20,
    type: "genre",
  },
  {
    id: "top-electronic",
    name: "Electronic Vibes",
    description: "Electronic and dance floor favorites",
    tag: "electronic",
    size: 20,
    type: "genre",
  },
  {
    id: "top-pop",
    name: "Pop Hits",
    description: "The pop tracks everyone's playing",
    tag: "pop",
    size: 20,
    type: "genre",
  },
  {
    id: "top-rnb",
    name: "R&B and Soul",
    description: "Smooth R&B and soul standouts",
    tag: "rnb",
    size: 20,
    type: "genre",
  },
  {
    id: "top-metal",
    name: "Metal Mayhem",
    description: "Heavy riffs and thunderous drums",
    tag: "metal",
    size: 20,
    type: "genre",
  },
  {
    id: "top-jazz",
    name: "Jazz Classics",
    description: "Timeless jazz from the greats",
    tag: "jazz",
    size: 20,
    type: "genre",
  },
  {
    id: "top-punk",
    name: "Punk Uncut",
    description: "Raw energy from CBGB to the present",
    tag: "punk",
    size: 20,
    type: "genre",
  },
  {
    id: "top-blues",
    name: "Blues Highway",
    description: "From Delta to Chicago, the roots that built it all",
    tag: "blues",
    size: 20,
    type: "genre",
  },
  {
    id: "top-folk",
    name: "Folk Revival",
    description: "Storytellers and fingerpickers across generations",
    tag: "folk",
    size: 20,
    type: "genre",
  },
  {
    id: "top-country",
    name: "Country Roads",
    description: "From outlaw anthems to stadium singalongs",
    tag: "country",
    size: 20,
    type: "genre",
  },
  {
    id: "top-reggae",
    name: "Reggae Rhythms",
    description: "One-drop grooves from Jamaica and beyond",
    tag: "reggae",
    size: 20,
    type: "genre",
  },
  {
    id: "top-soul",
    name: "Soul Kitchen",
    description: "The warmest voices and deepest grooves",
    tag: "soul",
    size: 20,
    type: "genre",
  },
  {
    id: "top-funk",
    name: "Funk Foundation",
    description: "The one. The groove that makes you move.",
    tag: "funk",
    size: 20,
    type: "genre",
  },
  {
    id: "top-latin",
    name: "Latin Heat",
    description: "Salsa, samba, and everything in between",
    tag: "latin",
    size: 20,
    type: "genre",
  },
  {
    id: "era-60s",
    name: "60s Revolution",
    description: "The soundtrack of peace, love, and rock & roll",
    tag: "60s",
    size: 20,
    type: "era",
  },
  {
    id: "era-70s",
    name: "70s Gold",
    description: "Disco, classic rock, and the birth of funk",
    tag: "70s",
    size: 20,
    type: "era",
  },
  {
    id: "era-80s",
    name: "80s Anthems",
    description: "The decade of big sounds and bigger hair",
    tag: "80s",
    size: 20,
    type: "era",
  },
  {
    id: "era-90s",
    name: "90s Nostalgia",
    description: "Grunge, Britpop, and golden-era hip-hop",
    tag: "90s",
    size: 20,
    type: "era",
  },
  {
    id: "era-00s",
    name: "00s Rewind",
    description: "Indie sleaze, crunk, and the iPod era",
    tag: "00s",
    size: 20,
    type: "era",
  },
  {
    id: "mood-chill",
    name: "Chill Vibes",
    description: "Laid-back tracks for unwinding",
    tag: "chill",
    size: 20,
    type: "mood",
  },
  {
    id: "mood-energetic",
    name: "Workout Energy",
    description: "High-energy tracks to power through",
    tag: "workout",
    size: 20,
    type: "mood",
  },
  {
    id: "mood-ambient",
    name: "Ambient Drift",
    description: "Weightless soundscapes for deep focus",
    tag: "ambient",
    size: 20,
    type: "mood",
  },
  {
    id: "mood-party",
    name: "Party Starter",
    description: "The crowd is waiting. You know what to do.",
    tag: "party",
    size: 20,
    type: "mood",
  },
  {
    id: "mood-rainy",
    name: "Rainy Day",
    description: "Songs for watching the rain hit the window",
    tag: "rainy day",
    size: 20,
    type: "mood",
  },
];

export const EDITORIAL_PLAYLIST_COUNT = 13;

export const selectEditorialPresets = () => {
  const pool = [...EDITORIAL_PLAYLIST_POOL];
  for (let i = 0; i < EDITORIAL_PLAYLIST_COUNT; i++) {
    const j = i + Math.floor(Math.random() * (pool.length - i));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, EDITORIAL_PLAYLIST_COUNT);
};
