name: CI

on:
  pull_request:
    branches: ["main", "test"]
    paths-ignore:
      - "*.md"
      - ".github/*.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "README.md"

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
